---
- name: Install dante
  import_tasks: dante.yml

- name: Init user
  when: user is defined
  import_tasks: user.yml

- name: Copy danted.conf
  template:
    src: danted.conf.j2
    dest: /etc/danted.conf
  notify: restart danted

- name: Upload danted script
  copy:
    src: danted
    dest: /etc/init.d/danted
    mode: 0755

- name: Start danted
  service:
    name: danted
    state: started
    enabled: yes
