---
- name: Install python for Ansible
  raw: test -e /usr/bin/python || (apt -qy update && apt install -y python-minimal)
  register: output
  changed_when: output.stdout

- name: Ensure apt cache is up to date
  apt: update_cache=yes cache_valid_time=3600 upgrade=dist
  changed_when: False

- name: install setfacl support
  apt: pkg=acl
